  - hosts: localhost
    connection: local
    become: true
    become_user: root
    tasks:
      - apt:
          update_cache: yes
          cache_valid_time: 3600
      - apt:
          name:
          - ubuntu-desktop
          - tasksel
          - slim
          - xorg
          - snapd
          - vlc
          - zlib1g-dev
          - python3
          - pip
          - jq
          - tux
          state: present
          update_cache: true
      - community.general.snap:
          name:
          - heroku
          - code
          - pycharm-community
          classic: yes
      - name: Install python packages
        ansible.builtin.pip:
          requirements: "./requirements.txt"
      - name: autoclean
        apt:
          autoclean: yes

